// pages/auth/register.vue
<!-- pages/auth/register.vue (avec middleware guest) -->
<template>
  <div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Créer un compte
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Ou
          <NuxtLink to="/auth/login" class="font-medium text-primary-600 hover:text-primary-500">
            connectez-vous si vous avez déjà un compte
          </NuxtLink>
        </p>
      </div>

      <div v-if="error" class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <AlertCircle class="h-5 w-5 text-red-400" />
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">Erreur</h3>
            <div class="mt-2 text-sm text-red-700">
              <p>{{ error }}</p>
            </div>
          </div>
          <div class="ml-auto pl-3">
            <div class="-mx-1.5 -my-1.5">
              <button @click="error = ''" type="button" class="inline-flex rounded-md bg-red-50 p-1.5 text-red-500 hover:bg-red-100 focus:outline-none">
                <span class="sr-only">Fermer</span>
                <XIcon class="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <div v-if="success" class="rounded-md bg-green-50 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <CheckCircle class="h-5 w-5 text-green-400" />
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-green-800">Succès</h3>
            <div class="mt-2 text-sm text-green-700">
              <p>{{ success }}</p>
            </div>
          </div>
        </div>
      </div>

      <div v-if="!registrationComplete" class="mt-8">
        <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
          <form @submit.prevent="register" class="space-y-6">
            <div>
              <label for="name" class="block text-sm font-medium text-gray-700">Nom complet</label>
              <div class="mt-1">
                <input
                    id="name"
                    v-model="formData.name"
                    name="name"
                    type="text"
                    autocomplete="name"
                    class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="Votre nom"
                />
              </div>
            </div>

            <div>
              <label for="email" class="block text-sm font-medium text-gray-700">
                Adresse email
                <span class="text-red-500">*</span>
              </label>
              <div class="mt-1">
                <input
                    id="email"
                    v-model="formData.email"
                    name="email"
                    type="email"
                    autocomplete="email"
                    required
                    class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="votre@email.com"
                />
              </div>
            </div>

            <div>
              <label for="phoneNumber" class="block text-sm font-medium text-gray-700">Numéro de téléphone</label>
              <div class="mt-1">
                <input
                    id="phoneNumber"
                    v-model="formData.phoneNumber"
                    name="phoneNumber"
                    type="tel"
                    autocomplete="tel"
                    class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="Votre numéro de téléphone"
                />
              </div>
            </div>

            <div>
              <label for="password" class="block text-sm font-medium text-gray-700">
                Mot de passe
                <span class="text-red-500">*</span>
              </label>
              <div class="mt-1">
                <input
                    id="password"
                    v-model="formData.password"
                    name="password"
                    type="password"
                    autocomplete="new-password"
                    required
                    class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="Créer un mot de passe"
                />
              </div>
              <p v-if="passwordError" class="mt-1 text-sm text-red-600">{{ passwordError }}</p>
              <p v-else class="mt-1 text-xs text-gray-500">Le mot de passe doit contenir au moins 8 caractères</p>
            </div>

            <div>
              <label for="passwordConfirm" class="block text-sm font-medium text-gray-700">
                Confirmer le mot de passe
                <span class="text-red-500">*</span>
              </label>
              <div class="mt-1">
                <input
                    id="passwordConfirm"
                    v-model="formData.passwordConfirm"
                    name="passwordConfirm"
                    type="password"
                    autocomplete="new-password"
                    required
                    class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                    placeholder="Confirmer le mot de passe"
                />
              </div>
              <p v-if="passwordConfirmError" class="mt-1 text-sm text-red-600">{{ passwordConfirmError }}</p>
            </div>

            <div class="flex items-center">
              <input
                  id="terms"
                  v-model="agreeToTerms"
                  type="checkbox"
                  class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                  required
              />
              <label for="terms" class="ml-2 block text-sm text-gray-900">
                J'accepte les
                <a href="#" class="text-primary-600 hover:text-primary-500">
                  conditions d'utilisation
                </a>
                et la
                <a href="#" class="text-primary-600 hover:text-primary-500">
                  politique de confidentialité
                </a>
              </label>
            </div>

            <div>
              <button
                  type="submit"
                  :disabled="isLoading || !isFormValid"
                  class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <svg v-if="isLoading" class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                S'inscrire
              </button>
            </div>
          </form>

          <div class="mt-6">
            <div class="relative">
              <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-gray-300"></div>
              </div>
              <div class="relative flex justify-center text-sm">
                <span class="px-2 bg-white text-gray-500">Ou s'inscrire avec</span>
              </div>
            </div>

            <div class="mt-6">
              <button
                  @click="handleGoogleLogin"
                  type="button"
                  :disabled="isGoogleLoading"
                  class="w-full flex justify-center items-center py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
              >
                <svg v-if="isGoogleLoading" class="animate-spin -ml-1 mr-3 h-5 w-5 text-gray-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <svg v-else class="h-5 w-5 mr-2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path fill="#EA4335" d="M5.26620003,9.76452941 C6.19878754,6.93863203 8.85444915,4.90909091 12,4.90909091 C13.6909091,4.90909091 15.2181818,5.50909091 16.4181818,6.49090909 L19.9090909,3 C17.7818182,1.14545455 15.0545455,0 12,0 C7.27006974,0 3.1977497,2.69829785 1.23999023,6.65002441 L5.26620003,9.76452941 Z" />
                  <path fill="#34A853" d="M16.0407269,18.0125889 C14.9509167,18.7163016 13.5660892,19.0909091 12,19.0909091 C8.86648613,19.0909091 6.21911939,17.076871 5.27698177,14.2678769 L1.23746264,17.3349879 C3.19279051,21.2936293 7.26500293,24 12,24 C14.9328362,24 17.7353462,22.9573905 19.834192,20.9995801 L16.0407269,18.0125889 Z" />
                  <path fill="#4A90E2" d="M19.834192,20.9995801 C22.0291676,18.9520994 23.4545455,15.903663 23.4545455,12 C23.4545455,11.2909091 23.3454545,10.5818182 23.1272727,9.90909091 L12,9.90909091 L12,14.4545455 L18.4363636,14.4545455 C18.1187732,16.013626 17.2662994,17.2212117 16.0407269,18.0125889 L19.834192,20.9995801 Z" />
                  <path fill="#FBBC05" d="M5.27698177,14.2678769 C5.03832634,13.556323 4.90909091,12.7937589 4.90909091,12 C4.90909091,11.2182781 5.03443647,10.4668121 5.26620003,9.76452941 L1.23999023,6.65002441 C0.43658717,8.26043162 0,10.0753848 0,12 C0,13.9195484 0.444780743,15.7301709 1.23746264,17.3349879 L5.27698177,14.2678769 Z" />
                </svg>
                Google
              </button>
            </div>
          </div>
        </div>
      </div>

      <div v-else class="mt-8 bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10 text-center">
        <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
          <CheckCircle class="h-6 w-6 text-green-600" />
        </div>
        <h3 class="mt-3 text-lg font-medium text-gray-900">Inscription réussie !</h3>
        <p class="mt-2 text-sm text-gray-500">
          Un email de vérification a été envoyé à {{ formData.email }}. Veuillez vérifier votre email pour activer votre compte.
        </p>
        <div class="mt-5">
          <NuxtLink to="/auth/login">
            <button
                type="button"
                class="inline-flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
            >
              Aller à la page de connexion
            </button>
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '~/stores/auth'
import { XIcon, CheckCircle, AlertCircle } from 'lucide-vue-next'

// Définir les métadonnées de la page pour utiliser le middleware guest
definePageMeta({
  middleware: ['guest']
})

const router = useRouter()
const authStore = useAuthStore()

const formData = ref({
  name: '',
  email: '',
  phoneNumber: '',
  password: '',
  passwordConfirm: '',
  emailVisibility: true
})

const agreeToTerms = ref(false)
const error = ref('')
const success = ref('')
const isLoading = ref(false)
const isGoogleLoading = ref(false)
const registrationComplete = ref(false)

// Validation
const passwordError = computed(() => {
  if (!formData.value.password) return ''

  if (formData.value.password.length < 8) {
    return 'Le mot de passe doit contenir au moins 8 caractères'
  }

  return ''
})

const passwordConfirmError = computed(() => {
  if (!formData.value.passwordConfirm) return ''

  if (formData.value.password !== formData.value.passwordConfirm) {
    return 'Les mots de passe ne correspondent pas'
  }

  return ''
})

const isFormValid = computed(() => {
  return (
      formData.value.email &&
      formData.value.password &&
      formData.value.passwordConfirm &&
      !passwordError.value &&
      !passwordConfirmError.value &&
      agreeToTerms.value
  )
})

async function register() {
  if (!isFormValid.value) return

  isLoading.value = true
  error.value = ''
  success.value = ''

  try {
    await authStore.register({
      ...formData.value
    })

    registrationComplete.value = true
    success.value = 'Inscription réussie ! Veuillez vérifier votre email pour activer votre compte.'
  } catch (err) {
    error.value = err.message || 'Erreur lors de l\'inscription. Veuillez réessayer.'
  } finally {
    isLoading.value = false
  }
}

async function handleGoogleLogin() {
  isGoogleLoading.value = true
  error.value = ''

  try {
    // Vérifiez d'abord si la méthode existe
    if (typeof authStore.loginWithGoogle !== 'function') {
      throw new Error("La méthode de connexion Google n'est pas disponible. Veuillez contacter l'administrateur.")
    }

    await authStore.loginWithGoogle()
    router.push('/')
  } catch (err) {
    console.error('Google login error:', err)
    error.value = err.message || 'Erreur de connexion avec Google. Veuillez réessayer.'
  } finally {
    isGoogleLoading.value = false
  }
}
</script>

// sba-mobile/app/(auth)/register.tsx
import React, { useState } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    ScrollView,
    KeyboardAvoidingView,
    Platform,
    ActivityIndicator,
    Image,
    Alert
} from 'react-native';
import { useRouter } from 'expo-router';
import { useAuth } from '@/contexts/AuthContext';
import { Ionicons } from '@expo/vector-icons';
import Input from '@/components/ui/Input';
import Button from '@/components/ui/Button';
import {Colors} from '@/constants/Colors';

export default function RegisterScreen() {
    const { register, loginWithGoogle } = useAuth();
    const router = useRouter();

    const [formData, setFormData] = useState({
        name: '',
        email: '',
        phoneNumber: '',
        password: '',
        passwordConfirm: '',
        emailVisibility: true
    });

    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [googleLoading, setGoogleLoading] = useState(false);
    const [agreeToTerms, setAgreeToTerms] = useState(false);
    const [registrationComplete, setRegistrationComplete] = useState(false);

    // Update form field
    const updateField = (field: string, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    // Basic validation
    const validateForm = () => {
        if (!formData.email.trim() || !formData.password.trim() || !formData.passwordConfirm.trim()) {
            setError('Veuillez remplir tous les champs obligatoires');
            return false;
        }

        // Email validation
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(formData.email)) {
            setError('Veuillez entrer une adresse email valide');
            return false;
        }

        // Password validation
        if (formData.password.length < 8) {
            setError('Le mot de passe doit contenir au moins 8 caractères');
            return false;
        }

        // Password confirmation
        if (formData.password !== formData.passwordConfirm) {
            setError('Les mots de passe ne correspondent pas');
            return false;
        }

        // Terms agreement
        if (!agreeToTerms) {
            setError('Vous devez accepter les conditions d\'utilisation');
            return false;
        }

        return true;
    };

    const handleRegister = async () => {
        if (!validateForm()) return;

        setError('');
        setIsLoading(true);

        try {
            await register(formData);

            setSuccess('Inscription réussie ! Veuillez vérifier votre email pour activer votre compte.');
            setRegistrationComplete(true);
        } catch (err: any) {
            setError(err.message || 'Erreur lors de l\'inscription. Veuillez réessayer.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleGoogleLogin = async () => {
        setGoogleLoading(true);
        setError('');

        try {
            await loginWithGoogle();
            router.replace('/');
        } catch (err: any) {
            setError(err.message || 'Erreur de connexion avec Google. Veuillez réessayer.');
        } finally {
            setGoogleLoading(false);
        }
    };

    const navigateToLogin = () => {
        router.push('/login');
    };

    return (
        <KeyboardAvoidingView
            style={styles.container}
            behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
            keyboardVerticalOffset={Platform.OS === 'ios' ? 64 : 0}
        >
            <ScrollView
                contentContainerStyle={styles.scrollContent}
                showsVerticalScrollIndicator={false}
            >
                <View style={styles.logoContainer}>
                    <Image
                        source={require('@/assets/logo.png')}
                        style={styles.logo}
                        resizeMode="contain"
                    />
                    <Text style={styles.appName}>Sport & Bien-être</Text>
                </View>

                {registrationComplete ? (
                    <View style={styles.successContainer}>
                        <View style={styles.successIconContainer}>
                            <Ionicons name="checkmark-circle" size={64} color={Colors.success} />
                        </View>
                        <Text style={styles.successTitle}>Inscription réussie !</Text>
                        <Text style={styles.successText}>
                            Un email de vérification a été envoyé à {formData.email}. Veuillez vérifier votre email pour activer votre compte.
                        </Text>
                        <Button
                            title="Aller à la page de connexion"
                            onPress={navigateToLogin}
                            style={styles.successButton}
                        />
                    </View>
                ) : (
                    <View style={styles.formContainer}>
                        <Text style={styles.title}>Créer un compte</Text>

                        {error ? (
                            <View style={styles.errorContainer}>
                                <Ionicons name="alert-circle" size={20} color={Colors.danger} />
                                <Text style={styles.errorText}>{error}</Text>
                            </View>
                        ) : success ? (
                            <View style={styles.successMessageContainer}>
                                <Ionicons name="checkmark-circle" size={20} color={Colors.success} />
                                <Text style={styles.successMessageText}>{success}</Text>
                            </View>
                        ) : null}

                        <Input
                            value={formData.name}
                            onChangeText={(value) => updateField('name', value)}
                            placeholder="Votre nom"
                            label="Nom complet"
                        />

                        <Input
                            value={formData.email}
                            onChangeText={(value) => updateField('email', value)}
                            placeholder="votre@email.com"
                            label="Adresse email"
                            keyboardType="email-address"
                            autoCapitalize="none"
                            required
                        />

                        <Input
                            value={formData.phoneNumber}
                            onChangeText={(value) => updateField('phoneNumber', value)}
                            placeholder="Votre numéro de téléphone"
                            label="Numéro de téléphone"
                            keyboardType="phone-pad"
                        />

                        <Input
                            value={formData.password}
                            onChangeText={(value) => updateField('password', value)}
                            placeholder="Créer un mot de passe"
                            label="Mot de passe"
                            secureTextEntry
                            required
                            helpText="Le mot de passe doit contenir au moins 8 caractères"
                        />

                        <Input
                            value={formData.passwordConfirm}
                            onChangeText={(value) => updateField('passwordConfirm', value)}
                            placeholder="Confirmer le mot de passe"
                            label="Confirmer le mot de passe"
                            secureTextEntry
                            required
                        />

                        <TouchableOpacity
                            style={styles.termsContainer}
                            onPress={() => setAgreeToTerms(!agreeToTerms)}
                            activeOpacity={0.7}
                        >
                            <View style={styles.checkbox}>
                                {agreeToTerms && (
                                    <Ionicons name="checkmark" size={16} color={Colors.primary} />
                                )}
                            </View>
                            <Text style={styles.termsText}>
                                J'accepte les{' '}
                                <Text style={styles.termsLink}>conditions d'utilisation</Text> et la{' '}
                                <Text style={styles.termsLink}>politique de confidentialité</Text>
                            </Text>
                        </TouchableOpacity>

                        <Button
                            title="S'inscrire"
                            onPress={handleRegister}
                            loading={isLoading}
                            disabled={isLoading}
                            fullWidth
                            style={styles.registerButton}
                        />

                        <View style={styles.orContainer}>
                            <View style={styles.divider} />
                            <Text style={styles.orText}>ou</Text>
                            <View style={styles.divider} />
                        </View>

                        <TouchableOpacity
                            style={styles.googleButton}
                            onPress={handleGoogleLogin}
                            disabled={googleLoading || isLoading}
                        >
                            {googleLoading ? (
                                <ActivityIndicator size="small" color={Colors.text} />
                            ) : (
                                <>
                                    <Image
                                        source={require('@/assets/google-logo.png')}
                                        style={styles.googleIcon}
                                    />
                                    <Text style={styles.googleButtonText}>Continuer avec Google</Text>
                                </>
                            )}
                        </TouchableOpacity>
                    </View>
                )}

                {!registrationComplete && (
                    <View style={styles.loginContainer}>
                        <Text style={styles.loginText}>Vous avez déjà un compte ?</Text>
                        <TouchableOpacity onPress={navigateToLogin}>
                            <Text style={styles.loginLink}>Se connecter</Text>
                        </TouchableOpacity>
                    </View>
                )}
            </ScrollView>
        </KeyboardAvoidingView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 24,
        paddingTop: 40,
        paddingBottom: 24,
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 24,
    },
    logo: {
        width: 60,
        height: 60,
        marginBottom: 12,
    },
    appName: {
        fontSize: 20,
        fontWeight: '700',
        color: Colors.primary,
    },
    formContainer: {
        backgroundColor: Colors.card,
        borderRadius: 12,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: Colors.text,
        marginBottom: 24,
        textAlign: 'center',
    },
    errorContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#fee2e2',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    errorText: {
        marginLeft: 8,
        flex: 1,
        color: Colors.danger,
        fontSize: 14,
    },
    successMessageContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#d1fae5',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    successMessageText: {
        marginLeft: 8,
        flex: 1,
        color: Colors.success,
        fontSize: 14,
    },
    termsContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 24,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderWidth: 2,
        borderColor: Colors.primary,
        borderRadius: 4,
        marginRight: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    termsText: {
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        color: Colors.textSecondary,
    },
    termsLink: {
        color: Colors.primary,
        fontWeight: '500',
    },
    registerButton: {
        height: 48,
    },
    orContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 20,
    },
    divider: {
        flex: 1,
        height: 1,
        backgroundColor: Colors.border,
    },
    orText: {
        color: Colors.textSecondary,
        paddingHorizontal: 16,
        fontSize: 14,
    },
    googleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.card,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        height: 48,
    },
    googleIcon: {
        width: 20,
        height: 20,
        marginRight: 12,
    },
    googleButtonText: {
        color: Colors.text,
        fontSize: 16,
        fontWeight: '500',
    },
    loginContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 24,
    },
    loginText: {
        color: Colors.textSecondary,
        fontSize: 14,
    },
    loginLink: {
        color: Colors.primary,
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 4,
    },
    // Success view
    successContainer: {
        backgroundColor: Colors.card,
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    successIconContainer: {
        marginBottom: 16,
    },
    successTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: Colors.text,
        marginBottom: 12,
    },
    successText: {
        fontSize: 14,
        color: Colors.textSecondary,
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    successButton: {
        minWidth: 200,
    },
});
